# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Arrows
  - trigger: ":>>"
    replace: "→"
  - trigger: ":<<"
    replace: "←"
  - trigger: ":^^"
    replace: "↑"
  - trigger: ":vv"
    replace: "↓"
  - trigger: ":<>"
    replace: "↔"

  # Emails
  - trigger: "@gr"
    replace: "gianni@runlevel6.org"
  - trigger: "@gf"
    replace: "gianni@freshline.io"

  # Addresses
  - trigger: "@addr"
    replace: "4 Ashby Pl., Toronto, ON, M5A 3E3"

  # Dates
  - trigger: "@date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: "@shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
