theme = "base16_default"

[editor]
scrolloff = 10
cursorline = true
cursorcolumn = true
text-width = 120

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"C-," = ":w"
