theme = "base16_default"

[editor]
scrolloff = 10
cursorline = true
cursorcolumn = true
text-width = 120

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"C-g" = ["keep_primary_selection"]
"," = [":w"]
"D" = ["delete_selection", "move_char_left"]
"V" = ["select_mode"]

J = ["extend_to_line_bounds", "select_mode"]                      # Select whole line, then select lines downwards
K = ["extend_to_line_bounds", "select_mode", "flip_selections"]   # Select whole line, then select lines upwards

"A-j" = "join_selections"          # Join lines
"A-J" = "join_selections_space"    # Join lines, selecting the space in between 

X = "remove_primary_selection"    # Remove primary selection
x = "keep_selections"             # Keep selections that match regex
"A-x" = "remove_selections"       # Remove selections that match regex

[keys.select]
J = ["extend_line_down", "extend_to_line_bounds"]
K = ["extend_line_up", "extend_to_line_bounds"]

"A-j" = "join_selections"
"A-J" = "join_selections_space"

X = "remove_primary_selection"
x = "keep_selections"
"A-x" = "remove_selections"
